# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Harvester < Formula
  desc "CLI tool for managing Harvester HCI clusters — create and control VMs, images, volumes, networks, and hosts."
  homepage "https://github.com/abonillabeeche/harvester-cli"
  version "0.3.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abonillabeeche/harvester-cli/releases/download/v0.3.3/harvester_0.3.3_darwin_amd64.tar.gz"
      sha256 "df8da765af9f90a879b3fc8ddd20f164e7178cb61848debc9c757573c95b11ff"

      define_method(:install) do
        bin.install "harvester"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abonillabeeche/harvester-cli/releases/download/v0.3.3/harvester_0.3.3_darwin_arm64.tar.gz"
      sha256 "cbb2b24567d7666005d9ee378310db3f789b8a78e3bf605ad2ebf8fbce10f8aa"

      define_method(:install) do
        bin.install "harvester"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abonillabeeche/harvester-cli/releases/download/v0.3.3/harvester_0.3.3_linux_amd64.tar.gz"
      sha256 "76824c99a3e0542faa955525a683ad5eca28e50723fc7c59c8ce6e1f2cb4d46c"
      define_method(:install) do
        bin.install "harvester"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abonillabeeche/harvester-cli/releases/download/v0.3.3/harvester_0.3.3_linux_arm64.tar.gz"
      sha256 "0bb3cb4c834eb46bec315de2e721cc0810a23d7dc08de4930175f23e863830db"
      define_method(:install) do
        bin.install "harvester"
      end
    end
  end

  test do
    system "#{bin}/harvester --version"
  end
end
