# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Harvester < Formula
  desc "CLI tool for managing Harvester HCI clusters — create and control VMs, images, volumes, networks, and hosts."
  homepage "https://github.com/abonillabeeche/harvester-cli"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abonillabeeche/harvester-cli/releases/download/v0.5.0/harvester_0.5.0_darwin_amd64.tar.gz"
      sha256 "32c3f460c87f510b4b0537eb08c60f5efac6a088431bc153ae117e53c7728d3b"

      define_method(:install) do
        bin.install "harvester"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abonillabeeche/harvester-cli/releases/download/v0.5.0/harvester_0.5.0_darwin_arm64.tar.gz"
      sha256 "b017ed18378d4b356ae473ec3326630f582018c446f92f9cd91e6c344a254cca"

      define_method(:install) do
        bin.install "harvester"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abonillabeeche/harvester-cli/releases/download/v0.5.0/harvester_0.5.0_linux_amd64.tar.gz"
      sha256 "cbe73277723982d33d3cb58df133f6d77884d71be082080c404411bed406814c"
      define_method(:install) do
        bin.install "harvester"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abonillabeeche/harvester-cli/releases/download/v0.5.0/harvester_0.5.0_linux_arm64.tar.gz"
      sha256 "e4056f08748fd2744463cd405d935e32dd2760e2c5fa29128536752e71cea396"
      define_method(:install) do
        bin.install "harvester"
      end
    end
  end

  test do
    system "#{bin}/harvester --version"
  end
end
